### ISSUE TITLE
JSON DB Loader for GeoJsons

### ISSUE THREAD

**Issue by lkno0705** [lkno0705/ISSTracker#28]

**Comment by lkno0705** [comment]
Suggest Python for easy and quick use

**Comment by BigKahuna7385** [comment]
´´´ XML 
<?xml version="1.0" encoding="UTF-8"?>
	<coordinates>		
			<point>
               <lon>9.921906</lon>
               <lat>54.983105</lat>
            </point>
            <point>
               <lon>9.93958</lon>
               <lat>54.59664</lat>
            </point>
            <point>
               <lon>10.950112</lon>
               <lat>54.363605</lat>
            </point>
            <point>
               <lon>10.939467</lon>
               <lat>54.008694</lat>
            </point>
            <point>
               <lon>11.956252</lon>
               <lat>54.196484</lat>
            </point>
            <point>
               <lon>12.51844</lon>
               <lat>54.47037</lat>
            </point>
            <point>
               <lon>13.647467</lon>
               <lat>54.075512</lat>
            </point>
            <point>
               <lon>14.119686</lon>
               <lat>53.75703</lat>
            </point>
            <point>
               <lon>14.353315</lon>
               <lat>53.248173</lat>
            </point>
            <point>
               <lon>14.074521</lon>
               <lat>52.981262</lat>
            </point>
            <point>
               <lon>14.4376</lon>
               <lat>52.62485</lat>
            </point>
            <point>
               <lon>14.685026</lon>
               <lat>52.089947</lat>
            </point>
            <point>
               <lon>14.607099</lon>
               <lat>51.74519</lat>
            </point>
            <point>
               <lon>15.016995</lon>
               <lat>51.106674</lat>
            </point>
            <point>
               <lon>14.570718</lon>
               <lat>51.00234</lat>
            </point>
            <point>
               <lon>14.3070135</lon>
               <lat>51.117268</lat>
            </point>
            <point>
               <lon>14.056228</lon>
               <lat>50.926918</lat>
            </point>
            <point>
               <lon>13.338132</lon>
               <lat>50.733234</lat>
            </point>
            <point>
               <lon>12.966837</lon>
               <lat>50.484077</lat>
            </point>
            <point>
               <lon>12.240111</lon>
               <lat>50.26634</lat>
            </point>
            <point>
               <lon>12.415191</lon>
               <lat>49.96912</lat>
            </point>
            <point>
               <lon>12.521024</lon>
               <lat>49.547417</lat>
            </point>
            <point>
               <lon>13.031329</lon>
               <lat>49.307068</lat>
            </point>
            <point>
               <lon>13.595945</lon>
               <lat>48.87717</lat>
            </point>
            <point>
               <lon>13.243358</lon>
               <lat>48.416115</lat>
            </point>
            <point>
               <lon>12.884103</lon>
               <lat>48.289146</lat>
            </point>
            <point>
               <lon>13.025851</lon>
               <lat>47.637585</lat>
            </point>
            <point>
               <lon>12.932627</lon>
               <lat>47.467644</lat>
            </point>
            <point>
               <lon>12.62076</lon>
               <lat>47.672386</lat>
            </point>
            <point>
               <lon>12.141357</lon>
               <lat>47.703083</lat>
            </point>
            <point>
               <lon>11.4264145</lon>
               <lat>47.523766</lat>
            </point>
            <point>
               <lon>10.544504</lon>
               <lat>47.5664</lat>
            </point>
            <point>
               <lon>10.402083</lon>
               <lat>47.302486</lat>
            </point>
            <point>
               <lon>9.896069</lon>
               <lat>47.580196</lat>
            </point>
            <point>
               <lon>9.594226</lon>
               <lat>47.52506</lat>
            </point>
            <point>
               <lon>8.522612</lon>
               <lat>47.830826</lat>
            </point>
            <point>
               <lon>8.317302</lon>
               <lat>47.61358</lat>
            </point>
            <point>
               <lon>7.466759</lon>
               <lat>47.620583</lat>
            </point>
            <point>
               <lon>7.5936766</lon>
               <lat>48.33302</lat>
            </point>
            <point>
               <lon>8.099278</lon>
               <lat>49.017784</lat>
            </point>
            <point>
               <lon>6.65823</lon>
               <lat>49.201958</lat>
            </point>
            <point>
               <lon>6.1863203</lon>
               <lat>49.463802</lat>
            </point>
            <point>
               <lon>6.242751</lon>
               <lat>49.902225</lat>
            </point>
            <point>
               <lon>6.043073</lon>
               <lat>50.12805</lat>
            </point>
            <point>
               <lon>6.156658</lon>
               <lat>50.803722</lat>
            </point>
            <point>
               <lon>5.988658</lon>
               <lat>51.851616</lat>
            </point>
            <point>
               <lon>6.5893965</lon>
               <lat>51.852028</lat>
            </point>
            <point>
               <lon>6.8428693</lon>
               <lat>52.22844</lat>
            </point>
            <point>
               <lon>7.0920534</lon>
               <lat>53.144043</lat>
            </point>
            <point>
               <lon>6.9051394</lon>
               <lat>53.482162</lat>
            </point>
            <point>
               <lon>7.100425</lon>
               <lat>53.69393</lat>
            </point>
            <point>
               <lon>7.9362392</lon>
               <lat>53.748295</lat>
            </point>
            <point>
               <lon>8.121706</lon>
               <lat>53.527794</lat>
            </point>
            <point>
               <lon>8.8007345</lon>
               <lat>54.020786</lat>
            </point>
            <point>
               <lon>8.572118</lon>
               <lat>54.395645</lat>
            </point>
            <point>
               <lon>8.526229</lon>
               <lat>54.96274</lat>
            </point>
            <point>
               <lon>9.282049</lon>
               <lat>54.830864</lat>
            </point>
            <point>
               <lon>9.921906</lon>
               <lat>54.983105</lat>
            </point>         
       </coordinates>     

       
´´´

**Comment by BigKahuna7385** [comment]
```XML
<?xml version="1.0" encoding="UTF-8"?>
<request>
	<requestName>country-Name</requestName>
	<data>
		<coordinates>		
			<point>
               <lon>9.921906</lon>
               <lat>54.983105</lat>
            </point>
            <point>
               <lon>9.93958</lon>
               <lat>54.59664</lat>
            </point>
            <point>
               <lon>10.950112</lon>
               <lat>54.363605</lat>
            </point>
            <point>
               <lon>10.939467</lon>
               <lat>54.008694</lat>
            </point>
            <point>
               <lon>11.956252</lon>
               <lat>54.196484</lat>
            </point>
            <point>
               <lon>12.51844</lon>
               <lat>54.47037</lat>
            </point>
            <point>
               <lon>13.647467</lon>
               <lat>54.075512</lat>
            </point>
            <point>
               <lon>14.119686</lon>
               <lat>53.75703</lat>
            </point>
            <point>
               <lon>14.353315</lon>
               <lat>53.248173</lat>
            </point>
            <point>
               <lon>14.074521</lon>
               <lat>52.981262</lat>
            </point>
            <point>
               <lon>14.4376</lon>
               <lat>52.62485</lat>
            </point>
            <point>
               <lon>14.685026</lon>
               <lat>52.089947</lat>
            </point>
            <point>
               <lon>14.607099</lon>
               <lat>51.74519</lat>
            </point>
            <point>
               <lon>15.016995</lon>
               <lat>51.106674</lat>
            </point>
            <point>
               <lon>14.570718</lon>
               <lat>51.00234</lat>
            </point>
            <point>
               <lon>14.3070135</lon>
               <lat>51.117268</lat>
            </point>
            <point>
               <lon>14.056228</lon>
               <lat>50.926918</lat>
            </point>
            <point>
               <lon>13.338132</lon>
               <lat>50.733234</lat>
            </point>
            <point>
               <lon>12.966837</lon>
               <lat>50.484077</lat>
            </point>
            <point>
               <lon>12.240111</lon>
               <lat>50.26634</lat>
            </point>
            <point>
               <lon>12.415191</lon>
               <lat>49.96912</lat>
            </point>
            <point>
               <lon>12.521024</lon>
               <lat>49.547417</lat>
            </point>
            <point>
               <lon>13.031329</lon>
               <lat>49.307068</lat>
            </point>
            <point>
               <lon>13.595945</lon>
               <lat>48.87717</lat>
            </point>
            <point>
               <lon>13.243358</lon>
               <lat>48.416115</lat>
            </point>
            <point>
               <lon>12.884103</lon>
               <lat>48.289146</lat>
            </point>
            <point>
               <lon>13.025851</lon>
               <lat>47.637585</lat>
            </point>
            <point>
               <lon>12.932627</lon>
               <lat>47.467644</lat>
            </point>
            <point>
               <lon>12.62076</lon>
               <lat>47.672386</lat>
            </point>
            <point>
               <lon>12.141357</lon>
               <lat>47.703083</lat>
            </point>
            <point>
               <lon>11.4264145</lon>
               <lat>47.523766</lat>
            </point>
            <point>
               <lon>10.544504</lon>
               <lat>47.5664</lat>
            </point>
            <point>
               <lon>10.402083</lon>
               <lat>47.302486</lat>
            </point>
            <point>
               <lon>9.896069</lon>
               <lat>47.580196</lat>
            </point>
            <point>
               <lon>9.594226</lon>
               <lat>47.52506</lat>
            </point>
            <point>
               <lon>8.522612</lon>
               <lat>47.830826</lat>
            </point>
            <point>
               <lon>8.317302</lon>
               <lat>47.61358</lat>
            </point>
            <point>
               <lon>7.466759</lon>
               <lat>47.620583</lat>
            </point>
            <point>
               <lon>7.5936766</lon>
               <lat>48.33302</lat>
            </point>
            <point>
               <lon>8.099278</lon>
               <lat>49.017784</lat>
            </point>
            <point>
               <lon>6.65823</lon>
               <lat>49.201958</lat>
            </point>
            <point>
               <lon>6.1863203</lon>
               <lat>49.463802</lat>
            </point>
            <point>
               <lon>6.242751</lon>
               <lat>49.902225</lat>
            </point>
            <point>
               <lon>6.043073</lon>
               <lat>50.12805</lat>
            </point>
            <point>
               <lon>6.156658</lon>
               <lat>50.803722</lat>
            </point>
            <point>
               <lon>5.988658</lon>
               <lat>51.851616</lat>
            </point>
            <point>
               <lon>6.5893965</lon>
               <lat>51.852028</lat>
            </point>
            <point>
               <lon>6.8428693</lon>
               <lat>52.22844</lat>
            </point>
            <point>
               <lon>7.0920534</lon>
               <lat>53.144043</lat>
            </point>
            <point>
               <lon>6.9051394</lon>
               <lat>53.482162</lat>
            </point>
            <point>
               <lon>7.100425</lon>
               <lat>53.69393</lat>
            </point>
            <point>
               <lon>7.9362392</lon>
               <lat>53.748295</lat>
            </point>
            <point>
               <lon>8.121706</lon>
               <lat>53.527794</lat>
            </point>
            <point>
               <lon>8.8007345</lon>
               <lat>54.020786</lat>
            </point>
            <point>
               <lon>8.572118</lon>
               <lat>54.395645</lat>
            </point>
            <point>
               <lon>8.526229</lon>
               <lat>54.96274</lat>
            </point>
            <point>
               <lon>9.282049</lon>
               <lat>54.830864</lat>
            </point>
            <point>
               <lon>9.921906</lon>
               <lat>54.983105</lat>
            </point>         
       </coordinates>     
	</data>
</request>
```

**Comment by lkno0705** [comment]
https://geojson-maps.ash.ms/
