### ISSUE TITLE
ISS Pos. API

### ISSUE THREAD

**Issue by lkno0705** [lkno0705/ISSTracker#3]

**Comment by BigKahuna7385** [comment]
- [ ] Array mit Pos. Daten letzte 24 h

**Comment by lkno0705** [comment]
- Return Data in Correct Data format -> Format isn't specified yet

**Comment by lkno0705** [comment]
Return data in a Dictionary which should look like this:
```Json
{
„requestname“: „ISSpos“,
„latitude“: Value,
„longitude“: Value
}
```
